### ISSUE TITLE
Enable message history on chat rooms

### ISSUE THREAD

**Issue by soosheehd** [MuresanIA/Buhai-Communications#68]
As a user, when I connect to a chat room, I should see older messages which were already sent on that chat room while I was not connected, sorted by most recent at the very bottom.

**Comment by MuresanIA** [comment]
They way I see this happening for the moment is:

I will implement for the message the following:

- Repository,
- Service,
- Rest controller,
- Relation Message Entity ManytoOne with the ChatRoom Entity,
- Relation  ChatRoom Entity OneToMany with the Message Entity.

This is all I got in mind for the moment.
